global:
  scrape_interval: 15s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'category'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['category:9093']

  - job_name: 'product'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['product:9094']

  - job_name: 'coupon'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['coupon:9095']

  - job_name: 'profile'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['profile:9097']