server:
  port: 9099

spring:
  application:
    name: payment
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/easytobuy
    driverClassName: org.postgresql.Driver
    username: amigoscode
    jpa:
      database-platform:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true
  jpa:
    generate-ddl: true
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
#Stripe Component
stripe:
  key:
    secret: sk_test_51BHtdmF5UXVWBfyDbykYhSBkz3ST90CMgBOaMXKAcL7gIuTi7cNawLmYh7xFe7fYnZcZB9Fn33XEIlURpwMapHic00MwQV0iiQ