server:
  port: 9096

spring:
  application:
    name: external-clients
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false

client:
  coupon:
    url: http://coupon